
services:
  postgres:
    container_name: postgres-users

    image: bitnami/postgresql:latest

    ports:
      - "5432:5432"

    environment:
      POSTGRES_USER : admin
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_users